services:
  zakupki-scraper:
    build: .
    container_name: zakupki_scraper
    restart: always
    volumes:
      # Монтирование папок для сохранения данных и состояния, чтобы они сохранялись вне контейнера
      - ./zakupki_data:/app/zakupki_data
      - ./settings:/app/settings